# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db2e681f4244670b0a460b6b50c83da1a774a9d0438b4611a8383d5eb80c45f8e1448dfc0c6de698760d62fc83b0f7e64cfc5c462d2a42cfb820b2fb46a91828

test:
  secret_key_base: c29b2110278fadbb95ec2da72110db577058ffb721895b8935adaba06b748b8968b21d0e88311556e307c261bd2630a473b75ebbf60885da4da750e436dbf726

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
